### ISSUE TITLE
Version 0.2.17 Build fails on FreeBSD

### ISSUE THREAD

**Issue by asomers** [sfackler/rust-native-tls#367]
native-tls version 0.2.17 fails to build on FreeBSD 16.0, with this error:
```
error[E0004]: non-exhaustive patterns: `Some(Protocol::Tlsv13)` not covered
   --> /home/somers/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/native-tls-0.2.17/src/imp/openssl.rs:61:22
    |
 61 |     options |= match min {
    |                      ^^^ pattern `Some(Protocol::Tlsv13)` not covered
    |
note: `Option<Protocol>` defined here
   --> /localhome/somers/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/src/rust/library/core/src/option.rs:600:1
    |
600 | pub enum Option<T> {
    | ^^^^^^^^^^^^^^^^^^
...
608 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ---- not covered
    = note: the matched value is of type `Option<Protocol>`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
 73 ~         },
 74 +         Some(Protocol::Tlsv13) => todo!()
    |

error[E0004]: non-exhaustive patterns: `Some(Protocol::Tlsv13)` not covered
   --> /home/somers/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/native-tls-0.2.17/src/imp/openssl.rs:75:22
    |
 75 |     options |= match max {
    |                      ^^^ pattern `Some(Protocol::Tlsv13)` not covered
    |
note: `Option<Protocol>` defined here
   --> /localhome/somers/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/src/rust/library/core/src/option.rs:600:1
    |
600 | pub enum Option<T> {
    | ^^^^^^^^^^^^^^^^^^
...
608 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ---- not covered
    = note: the matched value is of type `Option<Protocol>`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
 81 ~         },
 82 +         Some(Protocol::Tlsv13) => todo!()
    |

For more information about this error, try `rustc --explain E0004`.
```
Version 0.2.16 built OK.

**Comment by jessevz** [comment]
I have the same error for Debian Trixie

**Comment by olback** [comment]
I'd recommend yanking 0.2.17.

If you don't want to depend on a git repo you can pin a crates.io version like this: `native-tls = "=0.2.16"`.

**Comment by asbytes** [comment]
I was successful to install the crate using cargo by specifying needed version with --config option:
`cargo --config 'patch.crates-io.native-tls.git="https://github.com/rust-native-tls/rust-native-tls"' --config 'patch.crates-io.native-tls.tag="v0.2.16"' install my_crate_name`

**Comment by kornelski** [comment]
Fixed
